sudo: required
dist: trusty

language: cpp

os:
  - linux
  # - osx

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Debug


script:
  - git submodule update --init
  - mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=$CONFIG -D GFLAGS_BUILD_SHARED_LIBS=ON -D GFLAGS_BUILD_STATIC_LIBS=ON -D GFLAGS_BUILD_TESTING=ON -D COVERAGE=1 .. && cmake --build . --config $CONFIG
